### ISSUE TITLE
Cannot read property 'commit' of undefined

### ISSUE THREAD

**Issue by Blueforcer** [Helmisek/conventional-changelog-generator#1]
Hello im very new to github actions and want to use your changelog generator.
Unfortunally i get this error:

```
Run Helmisek/conventional-changelog-generator@v1.0.6-release
fetch all tags in repository...
fetched all 1 tags in repository.
sorted tags by semver.
showing up to 10 last tags...
tag 2021.1.18.2345
fetch all releases...
fetched all 1 releases.
current release index: -1
Error: TypeError: Cannot read property 'commit' of undefined
```

What does it means?

Thanks in advance

**Comment by quant-eagle** [comment]
Hello, thanks for reporting the issue.

Can you please post your configuration for this action too? 

It seems that the action wasn't able to fetch any commits. And also the range is quite off as the current release index shouldn't be -1.

**Comment by Blueforcer** [comment]
sure,

```
      - name: Changelog generation step
        uses: Helmisek/conventional-changelog-generator@v1.0.6-release
        id: changelog-generator
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          commit-types: "fix:Bug Fixes,feat:Features,refactor:Refactoring"
          current-tag: ${{ env.PACKET_VERSION }}
      - name: Print version
        run: echo ${{ env.PACKET_VERSION }}
      - name: Print changelog
        run: echo "${{steps.changelog-generator.outputs.changelog}}"
```

im not sure about the "current-tag".  right now im using a new tag wich is generated in the same workflow for release upload
